# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Hacklog
author: Behnam Azizi
avatar: /images/photo.jpg
email: behnam.azizi.13 [at] gmail [dot] com
icon-url: /images/bio-hazard-256.png
description: > # this means to ignore newlines until "baseurl:"
  Post exploitation diary
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://bazizi.github.io" # the base hostname & protocol for your site
#twitter_username: jekyllrb
github_username:  bazizi
paginate: 10
# Build settings
markdown: kramdown
gems: [jekyll-paginate]
